import Head from "next/head";
import Bottombar from "./components/Bottombar";
import Choise from "./components/Choise";
import Company from "./components/Company";
import Filling from "./components/Filling";
import Hero from "./components/Hero";
import Join from "./components/Join";
import Navbar from "./components/Navbar";
import News from "./components/News";
import Works from "./components/Works";
export default function Home() {
  return (
    <>
      <Head>
        <title>Decorative-web react</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Company />
        <Filling />
        <Works />
        <Choise />
        <News />
        <Join />
        <Bottombar />
      </main>
    </>
  );
}
